name: UI Tests  # Название пайплайна

on:
  push:
    branches: [ "main", "master" ] # Запускать тесты при пуше в эти ветки
  pull_request:
    branches: [ "main" ] # Запускать при создании PR

jobs:
  test:
    runs-on: ubuntu-latest # Используем чистую Linux машину

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Копируем код проекта на сервер

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        # ВОТ ТУТ ПРОИСХОДИТ "ДРУЖБА" СЕКРЕТОВ И КОДА
        env:
          # Слева: имя переменной, которую ждет твой Python-код (Config)
          # Справа: имя секрета, который ты создашь в настройках GitHub
          SITE_TEST_USER_LOGIN: ${{ secrets.SITE_TEST_USER_LOGIN }}
          SITE_TEST_USER_PASSWORD: ${{ secrets.SITE_TEST_USER_PASSWORD }}
          SITE_TEST_URL: ${{ secrets.SITE_TEST_URL }}
          HEADLESS: "true" # В CI всегда запускаем без окна браузера
        run: pytest